"""Interface text, EN / 繁中. Chinese is a draft (🔍 zh-names)."""
import streamlit as st

S = {
    # toolbar
    "nav_home": {"en": "Home", "zh": "主頁"},
    "nav_review": {"en": "🔍 To review", "zh": "🔍 待檢查"},
    "lang_switch": {"en": "中文", "zh": "English"},
    "theme_dark": {"en": "Dark", "zh": "深色"},
    "theme_light": {"en": "Light", "zh": "淺色"},
    "login": {"en": "Log in", "zh": "登入"},
    "login_help": {"en": "Accounts arrive with workout logging.", "zh": "帳戶功能將與訓練記錄一同推出。"},
    "tagline": {"en": "The realistic way to train", "zh": "最實際的訓練方法"},

    # home
    "your_programme": {"en": "Your programme", "zh": "你的計劃"},
    "today": {"en": "Today", "zh": "今天"},
    "rest_day": {"en": "Rest day", "zh": "休息日"},
    "rest_day_body": {"en": "Recover: eat well, sleep well. Next session: {next}.",
                      "zh": "好好休息：吃得好、睡得好。下一節：{next}。"},
    "open_today": {"en": "Open today's session", "zh": "開始今天的訓練"},
    "open_programme": {"en": "Open programme", "zh": "打開計劃"},
    "change_programme": {"en": "Change programme", "zh": "更換計劃"},
    "find_title": {"en": "Not sure where to start?", "zh": "不知從何開始？"},
    "find_body": {"en": "Answer five questions and RealiGym picks a programme for you.",
                  "zh": "回答五條問題，RealiGym 為你挑選合適的計劃。"},
    "find_button": {"en": "Find my programme", "zh": "尋找我的計劃"},
    "all_programmes": {"en": "All programmes", "zh": "所有計劃"},
    "view_programme": {"en": "View programme", "zh": "查看計劃"},
    "days_a_week": {"en": "{n} days a week", "zh": "每週 {n} 天"},
    "pros": {"en": "Good for", "zh": "優點"},
    "cons": {"en": "Trade-offs", "zh": "缺點"},
    "level_beginner": {"en": "beginner", "zh": "初學者"},
    "level_intermediate": {"en": "intermediate", "zh": "中級"},
    "level_advanced": {"en": "advanced", "zh": "進階"},
    "core_short": {"en": "Core", "zh": "核心"},
    "weekdays": {"en": ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
                 "zh": ["日", "一", "二", "三", "四", "五", "六"]},

    # onboarding
    "ob_title": {"en": "Find your programme", "zh": "尋找你的計劃"},
    "ob_intro": {"en": "Five quick questions. You can change your answers any time.",
                 "zh": "五條簡單問題，答案可隨時更改。"},
    "q_days": {"en": "How many days a week can you train?", "zh": "你每週可以訓練幾天？"},
    "q_exp": {"en": "How long have you been lifting?", "zh": "你有多少重訓經驗？"},
    "exp_beginner": {"en": "New, or under 6 months", "zh": "新手，或少於 6 個月"},
    "exp_intermediate": {"en": "6 months to 2 years, consistently", "zh": "持續 6 個月至 2 年"},
    "exp_advanced": {"en": "More than 2 years", "zh": "超過 2 年"},
    "q_equip": {"en": "Where will you train?", "zh": "你會在哪裏訓練？"},
    "equip_commercial": {"en": "A full commercial gym", "zh": "設備齊全的商業健身室"},
    "equip_limited": {"en": "A small gym with limited equipment (e.g. a clubhouse)",
                      "zh": "器材有限的小型健身室（例如會所）"},
    "q_time": {"en": "How long can each session be?", "zh": "每次訓練可以多長？"},
    "time_none": {"en": "No limit", "zh": "沒有限制"},
    "minutes": {"en": "{n} min", "zh": "{n} 分鐘"},
    "q_health": {"en": "Any injuries or health conditions, such as heart or blood pressure issues?",
                 "zh": "你有沒有傷患或健康狀況，例如心臟或血壓問題？"},
    "yes": {"en": "Yes", "zh": "有"},
    "no": {"en": "No", "zh": "沒有"},
    "ob_submit": {"en": "See my programme", "zh": "查看我的計劃"},
    "ob_result": {"en": "We recommend", "zh": "我們推薦"},
    "why": {"en": "Why this one", "zh": "推薦原因"},
    "heads_up": {"en": "Before you start", "zh": "開始前請注意"},
    "start_programme": {"en": "Start this programme", "zh": "開始這個計劃"},
    "browse_all": {"en": "Browse all programmes", "zh": "瀏覽所有計劃"},

    # programme page
    "setup": {"en": "Gym setup", "zh": "健身室類型"},
    "day": {"en": "Day", "zh": "訓練日"},
    "about_min": {"en": "About {n} min including warmup", "zh": "連熱身約 {n} 分鐘"},
    "short_on_time": {"en": "Short on time? Cut isolation exercises to 2 sets taken to failure (about {n} min).",
                      "zh": "時間不夠？將孤立動作減至 2 組並做到力竭（約 {n} 分鐘）。"},
    "warmup_title": {"en": "Warm up first (don't skip this)", "zh": "先熱身（不要跳過）"},
    "warmup_general": {"en": "1. Light cardio", "zh": "1. 輕量帶氧"},
    "warmup_dynamic": {"en": "2. Dynamic stretches, {reps} reps each", "zh": "2. 動態伸展，每個 {reps} 下"},
    "upper_body": {"en": "Upper body", "zh": "上肢"},
    "lower_body": {"en": "Lower body", "zh": "下肢"},
    "warmup_pyramid": {"en": "3. Pyramid sets before each exercise: use the warmup calculator inside each exercise.",
                       "zh": "3. 每個動作前做金字塔熱身組：使用動作內的熱身計算器。"},
    "superset_must": {"en": "Superset these two: they use the same machine.",
                      "zh": "這兩個動作必須超級組：使用同一部器械。"},
    "superset_never": {"en": "Don't superset these.", "zh": "不要以超級組進行。"},
    "superset_optional": {"en": "Can be supersetted if you're short on time.", "zh": "時間不夠可以超級組進行。"},
    "unit_reps": {"en": "reps", "zh": "下"},
    "unit_seconds": {"en": "s", "zh": "秒"},
    "unit_steps": {"en": "steps", "zh": "步"},
    "optional": {"en": "optional", "zh": "可選"},
    "rest": {"en": "Rest {lo}–{hi} min between sets", "zh": "每組之間休息 {lo}–{hi} 分鐘"},
    "effort": {"en": "Stop 1 rep short of failure; take the last set to failure.",
               "zh": "每組留 1 下餘力；最後一組做到力竭。"},
    "muscles": {"en": "Muscles", "zh": "訓練肌肉"},
    "equipment": {"en": "Equipment", "zh": "器材"},
    "video_placeholder": {"en": "Demo video coming soon", "zh": "示範影片即將推出"},
    "form_cues": {"en": "Form tips", "zh": "動作要點"},
    "warmup_calc": {"en": "Warmup calculator", "zh": "熱身計算器"},
    "working_weight": {"en": "Your working weight (kg)", "zh": "你的訓練重量（公斤）"},
    "warmup_none": {"en": "Light enough to start straight away.", "zh": "重量夠輕，可直接開始。"},
    "warmup_optional_note": {"en": "(optional)", "zh": "（可選）"},
    "alternatives": {"en": "Swap for", "zh": "可替換為"},
    "no_programme": {"en": "Pick a programme from the home page first.", "zh": "請先在主頁選擇計劃。"},

    # review page
    "review_title": {"en": "To review", "zh": "待檢查"},
    "review_intro": {"en": "Things to check before friends rely on them. Each one shows as 🔍 in the app.",
                     "zh": "在朋友使用前需要檢查的項目，於應用程式中以 🔍 標示。"},
    "review_places": {"en": "{n} places marked", "zh": "{n} 處標示"},
}


def tr(key: str, **params):
    lang = st.session_state.get("lang", "en")
    entry = S[key]
    value = entry.get(lang) or entry["en"]
    return value.format(**params) if params and isinstance(value, str) else value
